" Vim Configurations by HaoZhang
" Not sure what the following are doing. Copied from 
highlight Cursor guifg=white guibg=black
highlight iCursor guifg=white guibg=steelblue
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver100-iCursor
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10

" Enable the horizontal straight line under the cursor
:set cursorline
" Enable the line number
:set number
" Enable folding by syntax
":set foldmethod = syntax

set tabstop=4
set shiftwidth=4
set expandtab

" turn off expandtab in Makefiles
autocmd FileType make set noexpandtab

" make tab characters visiable
set nolist
" Highlight the word in a search
set hlsearch
" Enable incremental search
set incsearch
" Set the highlight color for the search
:highlight Search ctermbg=Blue ctermfg=White

" Key mapping
nmap <A-Up> <C-w>k
nmap <A-Down> <C-w>j
nmap <A-Left> <C-w>h
nmap <A-Right> <C-w>l

" Set auto indent
set autoindent

" Load pathogen.vim
" Reference link: https://github.com/tpope/vim-pathogen
" Note: Its seems putting vim-pathogen folder under bundle doesn't help
" vim recognizing pathogen. pathogen.vim must be put under autoload folder.
execute pathogen#infect()
syntax on
filetype plugin indent on

" Auto map .vlib syntax highlighting to .v syntax highlighting
autocmd BufNewFile,BufRead *.v,*.sv,*.vlib set filetype=verilog

" Add status line to display the file path and name
set laststatus=2
set statusline+=%F

" Display trailing spaces
set listchars=tab:!·,trail:·

