" Vim Configurations by HaoZhang
" Not sure what the following are doing. Copied from 
highlight Cursor guifg=white guibg=black
highlight iCursor guifg=white guibg=steelblue
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver100-iCursor
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10

" Enable the horizontal straight line under the cursor
:set cursorline
" Enable the line number
:set number
" Enable folding by syntax
":set foldmethod = syntax

" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" turn off expandtab in Makefiles
autocmd FileType make set noexpandtab

" make tab characters visiable
set nolist
" Highlight the word in a search
set hlsearch
" Enable incremental search
set incsearch
" Set the highlight color for the search
:highlight Search ctermbg=Blue ctermfg=White

" Key mapping
nmap <A-Up> <C-w>k
nmap <A-Down> <C-w>j
nmap <A-Left> <C-w>h
nmap <A-Right> <C-w>l

" Set auto indent
set autoindent

" Load pathogen.vim
" Reference link: https://github.com/tpope/vim-pathogen
" Note: Its seems putting vim-pathogen folder under bundle doesn't help
" vim recognizing pathogen. pathogen.vim must be put under autoload folder.
execute pathogen#infect()
syntax on
filetype plugin indent on

" Auto map .vlib syntax highlighting to .v syntax highlighting
autocmd BufNewFile,BufRead *.v,*.sv,*.vlib set filetype=verilog

" Makefile uses real tabs for syntax parsing
" If the filetype is Makefile then we need to use real tabs
" Tab auto expanding is disabled here and real tabs and trailing
" spaces are displayed as !··· and ···
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0 list listchars=tab:!·,trail:·

" Add status line to display the file path and name
set laststatus=2
set statusline+=%F

" Display current line number and column number
set statusline+=\ \ \ %l\:%c

" Display line percentage, modified flag, read only flag and file type
set statusline+=\ %P\ %L\ %m\ %r\ %y

" Display trailing spaces and tabs
" Way to disable list is set nolist
set list
" Display both trailing tabs and spaces, enable the following
" set listchars=tab:!·,trail:·
" Display only trailing spaces, enable the following
set listchars=trail:·

" Adding vimdiff color scheme
if &diff
    colorscheme evening
    syntax off
endif

" Buftabline settings
" Showing the buffers opened on the first tab line
let g:buftabline_show = 2
let g:buftabline_numbers = 1
let g:buftabline_indicators = 1
let g:buftabline_separators = 0

" Hot keys for switching between buffers
" Move to next buffer: F10
" Move to previous buffer: F9
nnoremap <F10> :bnext<CR>
nnoremap <F9> :bprev<CR>
